### PR TITLE
fixed #187

### LINKED ISSUE #187: Sip-servlet accepts to modify "CONTACT" header which is system header
Sip-servlet will through exception error when we modify "Contact" system header, but still accepts to modify uppercase "CONTACT" header. ex:
res.setAddressHeader("Contact", contact1); --> exception error
res.setAddressHeader("CONTACT", contact1); --> ok, we can modify header.

In SipServletResponseImpl.getModifiableRule() function:

if(hName.equals(ContactHeader.NAME) should be if(hName.equalsIgnoreCase(ContactHeader.NAME)

<a href="https://timer.scm.io/repos/568d57c1960600c479a206a7/issues/187/create?referer=github" target="_blank">Log Time</a>

### PR DESCRIPTION
**Pull request by xhoaluu**
@jaimecasero 
Please help me to review.

### CODE REVIEW

File: sip-servlets-impl/src/main/java/org/mobicents/servlet/sip/message/SipServletRequestImpl.java [hunk 1]
```diff
@@ -237,7 +237,7 @@ public ModifiableRule getModifiableRule(String headerName) {
 			}
 		}
 		
-		if(hName.equals(ContactHeader.NAME)) {
+		if(hName.equalsIgnoreCase(ContactHeader.NAME)) {
```
Comment (jaimecasero) [inline sip-servlets-impl/src/main/java/org/mobicents/servlet/sip/message/SipServletRequestImpl.java]: it seems the rest of headers were already using IgnoreCase, so it seems correct, lets merge it
